<a href="<?=$this->url('page', ['action' => 'add'])?>">Добавить страницу</a>
<table class="table">
    <thead>
        <th>№ страницы</th>
        <th>Название</th>
        <th>Описание</th>
        <th></th>
    </thead>
    <tbody>
    <?php foreach($pages as $page): ?>
        <tr>
            <td><?=$page->idpage?></td>
            <td><?=$page->title?></td>
            <td><?=$page->article?></td>
            <td><a href="<?=$this->url('page', ['action' => 'modify', 'id' => $page->idpage])?>">Редактировать</a> / <a href="<?=$this->url('page', ['action' => 'delete', 'id' => $page->idpage])?>">Удалить</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

