<h1 style="margin-bottom: 15px;">Типа админка</h1>
<div style="margin-bottom: 50px;"><a href="<?=$this->url('admin', ['action' => 'add'])?>">Добавить новый пост</a></div>
<table class="table">
    <thead>
        <th>#</th>
        <th>Название</th>
        <th>Краткое содержание</th>
        <th>Действие</th>
    </thead>
    <tbody>
        <?php foreach($blogs as $blog): ?>
            <tr>
                <td><?=$blog->idblog?></td>
                <td><a href="<?=$this->url('blog', ['action' => 'article', 'id' => $blog->idblog])?>"><?=$blog->title?></a></td>
                <td><?=$blog->article?></td>
                <td><a href="<?=$this->url('admin', ['action' => 'edit', 'id' => $blog->idblog])?>">Реадктировать</a> /
                    <a href="<?=$this->url('admin', ['action' => 'delete', 'id' => $blog->idblog])?>">Удалить</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>