<?php
    $title = 'Добавление новой статьи';
    $this->headTitle();
?>
<h1><?=$title?></h1>
<?php
$form->setAttribute('action', $this->url('blog', ['action' => 'edit', 'id' => $this->id]));
$form->get('submit')->setAttribute('value', 'Edit');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idblog'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('article'));
echo $this->formRow($form->get('text'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();
?>